name: ci

on:
  push:
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v6,linux/arm/v7 \
            --load \
            -t "screenly-ose-webview-builder" \
            --output "type=image,push=false" \
            --file Dockerfile .
      -
        name: Run webviewer build
        run: |
          docker run \
            -v $(pwd):/build \
            screenly-ose-webview-builder build.sh
